# Project information
site_name: 'Antonio Cloud'
site_description: 'Antonio Cloud, personal website by Antonio Feijao UK, AWS Solutions Architect, technology, aws, python 3, rpi, raspberry pi, linux, open source, security, networking'
site_author: 'Antonio Feijao UK'

site_url: 'https://www.antoniocloud.com/'

repo_name: 'www.antoniocloud.com'
repo_url: 'https://github.com/AntonioFeijaoUK/www.antoniocloud.com'

# Theme
theme:
  name: 'material'
  language: 'en'
  logo:
    icon: 'cloud_done'
  favicon: '/images/favicon.ico'
  palette:
    primary: 'blue'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true

# Customization    
extra:
  disqus: 'antoniocloud'
  manifest: 'manifest.webmanifest'
  social:
    - type: 'linkedin'
      link: 'https://linkedin.com/in/antoniofeijaouk/'
    - type: 'github'
      link: 'https://github.com/antoniofeijaouk/'
    - type: 'twitter'
      link: 'https://twitter.com/antoniofeijaouk/'
    - type: 'instagram'
      link: 'https://www.instagram.com/AntonioFeijaoUK/'
  search:
    tokenizer: '[\s\-\.]+'

google_analytics: [ 'UA-131227949-1', 'auto']

extra_css:
  - 'assets/stylesheets/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - fontawesome_markdown

# Copyright
copyright: 'Copyright &copy; 2019 Antonio Feijao'

