# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

description: >- # this means to ignore newlines until "baseurl:"
  "Antonio.Cloud is Antonio Feijao UK, AWS Infrastructure Architect at Genomics England,
  with Advanced Networking and Security speciality certifications.
  Enabling other to deliver genomic healthcare and accelerate genomic research!
  **This is my personal website, opinions are my own**"

title: "Antonio.Cloud, Antonio Feijao UK, AWS Infrastructure Architect at Genomics England"

email: "antoniofeijao@gmail.com"

baseurl:

twitter_username: AntonioFeijaoUK

github_username:  AntonioFeijaoUK

## skins https://mmistakes.github.io/minimal-mistakes/docs/configuration/
minimal_mistakes_skin: dark  #dark #contrast #air #default: 'default'

search: true

locale: "en-GB"

# Build settings
markdown: kramdown

remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/

paginate: 5 # amount of posts to show

paginate_path: /page:num/

timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Antonio Feijao UK"
  avatar : "/assets/images/antonio-feijao-uk-logo.jpg"
  bio    : "AWS Infrastructure Architect at Genomics England, with `Advanced Networking` and `Security` `Speciality certifications`.
**Opinions are my own**"
  location: "London, United Kingdom"
  links:
    - label: "<script type='text/javascript' src='https://ko-fi.com/widgets/widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Buy-me-a-coffee', '#ff5e5b', 'B0B019526');kofiwidget2.draw();</script>"
      icon: "fas fa-fw fa-coffee"
      url: "https://ko-fi.com/B0B019526"
    - label: "Antonio.Cloud"
      icon: "fas fa-fw fa-link"
      url: "https://Antonio.Cloud"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/AntonioFeijaoUK/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AntonioFeijaoUK"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AntonioFeijaoUK"
      

footer:
  links:
    - label: "Antonio.Cloud"
      icon: "fas fa-fw fa-link"
      url: "https://antonio.cloud"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/AntonioFeijaoUK/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AntonioFeijaoUK"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AntonioFeijaoUK"
    

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

show_downloads: false


# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#comments

comments:
  provider: "disqus"
  disqus:
    shortname: "antoniocloud"
    

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-131227949-1"
    anonymize_ip: false # default
