theme: jekyll-theme-primer

github:
  private: true
  license:
    name: MIT
  source:
    branch: "gh-pages"
    path: "/"
  repository_url: "https://github.com/AntonioFeijaoUK/antonio-dot-cloud"
  
title: Antonio Cloud, Antonio Feijao UK
description: "Antonio.Cloud is the personal website of Antonio Feijao UK, Solutions Architect (SA) at Amazon Web Services (AWS). Antonio Feijao UK has speciality certifications of Advanced Networking and Security for the AWS Cloud. Antonio Feijao UK helps customers building secure, high-performing, resilient, and efficient infrastructure for their applications and workloads."
#This is my personal website.
#**The opinions expressed here are my own and do not necessarily represent those of current or past employers.**"
  
google_analytics: UA-131227949-1


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


nav:
  - title: Home
    url: "/"
  - title: About
    url: about.html


